{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "3acd2511",
   "metadata": {},
   "outputs": [],
   "source": [
    "class MyString:\n",
    "    \n",
    "    def lower(x):    \n",
    "        l = ''\n",
    "        for i in x:        \n",
    "            if ord(i) >= 65 and ord(i) <= 90:\n",
    "                l = l + chr(ord(i)+32)\n",
    "            else:\n",
    "                l = l + i \n",
    "        return l\n",
    "\n",
    "\n",
    "    def islower(x):    \n",
    "        for i in x:  \n",
    "            if ord(i) >=65 and ord(i) <=90:            \n",
    "                return False        \n",
    "        return True\n",
    "\n",
    "\n",
    "    def upper(x):\n",
    "        u = ''\n",
    "        for i in x:        \n",
    "            if ord(i) >= 97 and ord(i) <= 122:\n",
    "                u = u + chr(ord(i)-32)\n",
    "            else:\n",
    "                u = u + i \n",
    "        return u\n",
    "\n",
    "\n",
    "    def isupper(x):   \n",
    "        for i in x:  \n",
    "            if ord(i) >= 97 and ord(i) <= 122:            \n",
    "                return False        \n",
    "        return True\n",
    "\n",
    "\n",
    "    def capitalize(x):    \n",
    "        new = ''\n",
    "        for i in range(len(x)):        \n",
    "            if i == 0:\n",
    "                if (ord(x[i]) >=97 and ord(x[i]) <=122):\n",
    "                    new += chr(ord(x[i])-32)\n",
    "                else:\n",
    "                    new += x[i]\n",
    "            elif (ord(x[i]) >=65 and ord(x[i]) <=90):\n",
    "                new += chr(ord(x[i])+32)\n",
    "            else:\n",
    "                new+= x[i]\n",
    "\n",
    "        return new\n",
    "\n",
    "    \n",
    "    def swapcase(x):   \n",
    "        new=''\n",
    "        for i in x:\n",
    "            if (ord(i) >=65 and ord(i) <=90):\n",
    "                new += chr(ord(i)+32)\n",
    "            elif (ord(i) >=97 and ord(i) <=122):\n",
    "                new += chr(ord(i)-32)\n",
    "            else:\n",
    "                new += i\n",
    "        return new\n",
    "    \n",
    "\n",
    "    def title(x):    \n",
    "        new=''\n",
    "        for i in range(len(x)):\n",
    "            if i == 0 or (x[i-1] == ' ' or x[i-1] == \"'\"):\n",
    "                if (ord(x[i]) >=97 and ord(x[i]) <=122): \n",
    "                    new += chr(ord(x[i])-32)\n",
    "                else:\n",
    "                    new += x[i]          \n",
    "            elif (ord(x[i]) >= 65 and ord(x[i]) <=90):\n",
    "                new += chr(ord(x[i])+32)\n",
    "            else: \n",
    "                new = new + x[i]\n",
    "        return new   \n",
    "    \n",
    "    \n",
    "    def lstrip(x,sep = ' '):    \n",
    "        start = 0\n",
    "        for i in range(len(x)):\n",
    "            if x[i] in sep: \n",
    "                start = i+1\n",
    "            else:\n",
    "                break\n",
    "        return x[start::]     \n",
    "    \n",
    "    \n",
    "    def rstrip(x,sep = ' '):\n",
    "        stop = len(x)\n",
    "        for i in range(len(x)):\n",
    "            if x[-(i+1)] in sep:\n",
    "                stop = len(x)-1-i\n",
    "            else:\n",
    "                break\n",
    "        return x[:stop:] \n",
    "    \n",
    "    \n",
    "    def strip(x,sep = ' '):    \n",
    "        start, stop = 0, len(x)\n",
    "        for i in range(len(x)):\n",
    "            if x[i] in sep: \n",
    "                start = i+1\n",
    "            else:\n",
    "                break\n",
    "        for i in range(len(x)):\n",
    "            if x[-(i+1)] in sep:\n",
    "                stop = len(x)-1-i\n",
    "            else:\n",
    "                break\n",
    "        return x[start:stop:]\n",
    "    \n",
    "    \n",
    "    def removeprefix(x,prefix = ' '):\n",
    "        if prefix[0] == x[0] and prefix in x:        \n",
    "            return x[len(prefix)::] \n",
    "        return x\n",
    "    \n",
    "    \n",
    "    def removesuffix(x,suffix = ' '):\n",
    "        if suffix[-1] == x[-1] and suffix in x: \n",
    "            return x[:-len(suffix)]  \n",
    "        return x\n",
    "    \n",
    "    \n",
    "    def split(x,sep =' ',  maxsplit= -1): \n",
    "        new=''\n",
    "        splitnew = []\n",
    "\n",
    "        for i in range(len(x)):    \n",
    "            if x[i] != sep:\n",
    "                new += x[i]\n",
    "            elif x[i] != ' ' or new != '':\n",
    "                splitnew = splitnew + list([new])\n",
    "                new=''\n",
    "                if len(splitnew) == maxsplit:\n",
    "                    new = x[i+1:]\n",
    "                    break\n",
    "        if x[i] != ' ' or new != '':\n",
    "            splitnew = splitnew + list([new])\n",
    "        return splitnew\n",
    "    \n",
    "    \n",
    "    \n",
    "    def rsplit(x,sep = ' ',  maxsplit= -1):\n",
    "        new=''\n",
    "        splitnew = []\n",
    "\n",
    "        for i in range(len(x)-1, -1 ,-1):    \n",
    "            if x[i] != sep:\n",
    "                new += x[i]\n",
    "            elif x[i] != ' ' or new != '':\n",
    "                splitnew = splitnew + list([new[::-1]])\n",
    "                new=''\n",
    "                if len(splitnew) == maxsplit:\n",
    "                    new = x[i+1:]\n",
    "                    break\n",
    "        if x[i] != ' ' or new != '':\n",
    "            splitnew = splitnew + list([new])\n",
    "        return splitnew[::-1]\n",
    "    \n",
    "    \n",
    "    \n",
    "    def partition(x,sep): \n",
    "        if sep in x:\n",
    "            for i in range(len(x)):\n",
    "                if x[i] != sep:\n",
    "                    stop = i+1\n",
    "                else:\n",
    "                    break\n",
    "            return x[:stop], sep, x[stop+1:]    \n",
    "        else:\n",
    "            return x, '', ''\n",
    "        \n",
    "        \n",
    "        \n",
    "    def rpartition(x,sep):\n",
    "        if sep in x:\n",
    "            for i in range(len(x)):\n",
    "                if x[-(i+1)] != sep:\n",
    "                    stop = -(i+1)-1\n",
    "                else:\n",
    "                    break\n",
    "            return x[:stop], sep, x[stop+1:]     \n",
    "        else:\n",
    "            return '', '', x\n",
    "        \n",
    "\n",
    "        \n",
    "    def zfill(x,width):\n",
    "        if len(x) >= width:\n",
    "            return x \n",
    "        if x[0] in ('+','-'):\n",
    "            return x[0] + str(0)*(width-len(x)) + x[1:]\n",
    "        return str(0)*(width-len(x)) + x \n",
    "    \n",
    "    \n",
    "    \n",
    "    def ljust(x,width, fillchar = ' '): \n",
    "        if len(x) >= width:\n",
    "            return x \n",
    "        fillcount = width - len(x)\n",
    "        return x + fillchar*fillcount\n",
    "    \n",
    "    \n",
    "    \n",
    "    def rjust(x,width, fillchar = ' '):\n",
    "        if len(x) >= width:\n",
    "            return x \n",
    "        fillcount = width - len(x)\n",
    "        return fillchar*fillcount + x\n",
    "    \n",
    "    \n",
    "    def center(x,width, fillchar = ' '):\n",
    "        if len(x) >= width:\n",
    "            return x  \n",
    "        fillcount = width - len(x)\n",
    "        if fillcount % 2 == 0:\n",
    "            return fillchar*int((fillcount/2)) + x + fillchar*int((fillcount/2))\n",
    "        else:\n",
    "            return fillchar*int(((fillcount-1)/2)) + x + fillchar*int(((fillcount+1)/2))\n",
    "\n",
    "    \n",
    "    def find(x,sub, *args):\n",
    "        if args == ():\n",
    "            start, end = 0, len(x) \n",
    "        else:\n",
    "            start, end = args[0], args[1]\n",
    "\n",
    "        sl = len(sub)\n",
    "        if sub in x:\n",
    "            for i in range(start, end):\n",
    "                if x[i:i+sl] == sub:\n",
    "                    return i\n",
    "        return -1\n",
    "    \n",
    "    \n",
    "    def rfind(x,sub, *args):\n",
    "        if args == ():\n",
    "            start, end = 0, len(x) \n",
    "        else:\n",
    "            start, end = args[0], args[1]\n",
    "\n",
    "        sl = len(sub)\n",
    "        if sub in x:\n",
    "            for i in range(end, start, -1):\n",
    "                if x[i-sl:i] == sub:\n",
    "                    return (i-sl)\n",
    "        return -1\n",
    "    \n",
    "    \n",
    "    \n",
    "    def index(x,sub, *args):\n",
    "        if args == ():\n",
    "            start, end = 0, len(x) \n",
    "        else:\n",
    "            start, end = args[0], args[1]\n",
    "\n",
    "        sl = len(sub)\n",
    "        if sub in x:\n",
    "            for i in range(start, end):\n",
    "                if x[i:i+sl] == sub:\n",
    "                    return i\n",
    "        raise ValueError(f'substring not found')\n",
    "        \n",
    "        \n",
    "    \n",
    "    def rindex(x,sub, *args):\n",
    "        if args == ():\n",
    "            start, end = 0, len(x) \n",
    "        else:\n",
    "            start, end = args[0], args[1]\n",
    "\n",
    "        sl = len(sub)\n",
    "        if sub in x:\n",
    "            for i in range(end, start, -1):\n",
    "                if x[i-sl:i] == sub:\n",
    "                    return (i-sl)\n",
    "        raise ValueError(f'substring not found') \n",
    "        \n",
    "        \n",
    "        \n",
    "    def replace(x,old, new, count = -1):\n",
    "        ol, nl = len(old), len(new)\n",
    "        if old in x:\n",
    "            i, c = 0, 0\n",
    "            while i <= len(x):\n",
    "                if x[i:ol+i] == old:\n",
    "                    x = x[:i]+new+x[i+ol:]\n",
    "                    i+=nl\n",
    "                    c +=1\n",
    "                    if c == -1:\n",
    "                        continue\n",
    "                    elif c == count:\n",
    "                        break\n",
    "                i+=1\n",
    "            return x\n",
    "        return x\n",
    "    \n",
    "\n",
    "    \n",
    "    def count(x,sub, *args):\n",
    "        if args == ():\n",
    "            start, end = 0, len(x) \n",
    "        else:\n",
    "            start, end = args[0], args[1]\n",
    "        c = 0\n",
    "        sl = len(sub)\n",
    "        if sub in x and sub != '':\n",
    "            i = start\n",
    "            while i <= end:\n",
    "                if x[i:i+sl] == sub:\n",
    "                    c+=1\n",
    "                    i = i+sl\n",
    "                else:\n",
    "                    i += 1\n",
    "            return c   \n",
    "        elif sub == '':\n",
    "            return len(x)+1\n",
    "        else:\n",
    "            return 0         \n",
    "        \n",
    "        \n",
    "        \n",
    "    def startswith(x,prefix, *args):\n",
    "        if args == ():\n",
    "            start, end = 0, len(x)\n",
    "        else:\n",
    "            start, end = args[0], args[1]\n",
    "\n",
    "        for i in range(start,end):\n",
    "            for i in prefix:\n",
    "                if i == x[:len(prefix)]:\n",
    "                    return True\n",
    "            return False\n",
    "        \n",
    "        \n",
    "        \n",
    "    def endswith(x,suffix, *args):\n",
    "        if args == ():\n",
    "            start, end = 0, len(x)\n",
    "        else:\n",
    "            start, end = args[0], args[1]\n",
    "\n",
    "        for i in suffix:\n",
    "            if i == x[len(x)-len(suffix):]:\n",
    "                return True\n",
    "        return False\n",
    "    \n",
    "    \n",
    "    \n",
    "    def isalpha(x): \n",
    "        if x != '':\n",
    "            for i in x:\n",
    "                if ord(i) not in range(65,91) and ord(i) not in range(97,123):\n",
    "                    return False\n",
    "            return True\n",
    "        return False\n",
    "    \n",
    "    \n",
    "    \n",
    "    def isalnum(x):\n",
    "        if x != '':\n",
    "            for i in x:\n",
    "                if ord(i) not in range(65,91) and ord(i) not in range(97,123) and ord(i) not in range(48,58):\n",
    "                    return False\n",
    "            return True\n",
    "        return False\n",
    "    \n",
    "    \n",
    "    \n",
    "    def isascii(x):\n",
    "        if x != '':\n",
    "            for i in x:\n",
    "                if ord(i) not in range(0,128):\n",
    "                    return False\n",
    "        return True\n",
    "    \n",
    " \n",
    "\n",
    "    def isnumeric(x):\n",
    "        if x != '':\n",
    "            for i in x:\n",
    "                if ord(i) not in range(48,58):\n",
    "                    return False\n",
    "        return True\n",
    "    \n",
    "    \n",
    "    \n",
    "    def isprintable(x): \n",
    "        for i in x:\n",
    "            if ord(i) not in range(32,256):\n",
    "                return False\n",
    "        return True\n",
    "    \n",
    "    \n",
    "    \n",
    "    def isspace(x):  \n",
    "        if x != '':\n",
    "            for i in x:\n",
    "                if ord(i) != 32:\n",
    "                    return False\n",
    "            return True\n",
    "        return False\n",
    "    \n",
    "    \n",
    "    \n",
    "    def istitle(x):\n",
    "        for i in range(len(x)):\n",
    "            if i == 0 or (x[i-1] == ' ' or x[i-1] == \"'\") :\n",
    "                if ord(x[i]) not in range(65, 91):\n",
    "                    return False\n",
    "            elif ord(x[i]) in range(65, 91):\n",
    "                return False\n",
    "        return True   \n",
    "    \n",
    "    \n",
    "    \n",
    "    def join(itr, sep=''):\n",
    "        new = ''\n",
    "        for i in itr:\n",
    "            new += (i + sep)\n",
    "        return new[:len(new)-1]\n",
    "    \n",
    "    \n",
    "    \n",
    "    import multipledispatch\n",
    "    from multipledispatch import dispatch\n",
    "    @dispatch(str,str)\n",
    "    def concat(self,a,b):\n",
    "        return a+b\n",
    "\n",
    "    @dispatch(str,int)\n",
    "    def repeat(self,a,b):\n",
    "        return a*b\n",
    "    \n",
    "    @dispatch(str)\n",
    "    def length(self,a):\n",
    "        count=0\n",
    "        for i in a:\n",
    "            count+=1\n",
    "        return count\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
